<?php
function featured_ajax_menu() {
    $items['path-to-ajax/%/%'] = array(
            'access arguments' => array('access content'),
            'page callback' => 'featured_ajax_ajax_callback',
            'page arguments' => array(1,2),
            'type' => MENU_CALLBACK,
    );
    return $items;
}

function featured_ajax_ajax_callback($js, $node_id) {
  $node = node_load($node_id);

  if ($js == 'nojs') {
    drupal_goto('node/' . $node->nid);
  }

  // Get node data as array, render it into HTML
  $build = node_view($node);
  $html = render($build);

  // Prepare ajax command to insert the node's HTML into our div under News - the wrapper.
  $commands = array();
  $commands[] = ajax_command_html('#featured_ajax-ajax-wrapper', $html);

  // Render commands into JSON and print them to the browser.
  print ajax_render($commands);
  exit;  // Exit so Drupal doesn't rebuild page.
}
